[cryptoMaterial]

certPath = "conf"

useSMCrypto = false

[network]

peers=["172.17.6.233:20200","172.17.6.233:20201","172.17.6.233:20202","172.17.6.233:20203"]

defaultGroup="group0"

[account]

keyStoreDir="account"

accountAddress=""

accountFileFormat="pem"

password=""

accountFilePath=""

[threadPool]

channelProcessorThreadSize=16

receiptProcessorThreadSize=16

maxBlockingQueueSize=102400
